### ISSUE TITLE
Support for unpkg.com ?

### ISSUE THREAD

**Issue by asvny** [cxs-css/cxs#100]
As of now, the dist files served  by unpkg.com/cxs can't be used (it is in commonjs format) .So, it requires a change in the build system ..Wondering, whether you'll accept a PR ?

Ref: https://mobile.twitter.com/asvny_/status/1037474295822278656

**Comment by richard-lopes** [comment]
Yes! Please do.

**Comment by asvny** [comment]
@richard-lopes  I have submitted a new PR addressing this issue #101

**Comment by richard-lopes** [comment]
This is lovely. I will try it out this weekend.

**Comment by richard-lopes** [comment]
Thanks @asvny - A lot of good stuff. It is merged.

**Comment by asvny** [comment]
@richard-lopes  Thank you !
